### PR TITLE
Auto create floating ip and attach to a port during provisioning

### PR DESCRIPTION
**Pull request by skanthed**

### CODE REVIEW

**Comment by skanthed** [comment]
@tzumainn 
Should we prompt the user to set the `ESI_EXTERNAL_NETWORK` configuration in Horizon, or should we set it to a default value automatically?

**Comment by tzumainn** [comment]
> @tzumainn Should we prompt the user to set the `ESI_EXTERNAL_NETWORK` configuration in Horizon, or should we set it to a default value automatically?

There's no way to prompt it in Horizon; I'd say add an additional `Configuration` section in the README.

**Comment by skanthed** [comment]
@tzumainn Updated it with a readme section.

**Review by tzumainn — APPROVED** [review]
Looks good - thanks!

**Pull request merged**
